"""tools/resume.md記載の英語技術用語のVOICEVOXユーザー辞書定義"""

from voicevox_core import UserDictWord

RESUME_USER_DICT_WORDS: list[UserDictWord] = [
    # AWSサービス・クラウド関連
    UserDictWord(surface="AWS", pronunciation="エーダブリューエス", word_type="PROPER_NOUN", priority=9, accent_type=0),
    UserDictWord(surface="Lambda", pronunciation="ラムダ", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="S3", pronunciation="エススリー", word_type="PROPER_NOUN", priority=9, accent_type=2),
    UserDictWord(surface="EC2", pronunciation="イーシーツー", word_type="PROPER_NOUN", priority=9, accent_type=0),
    UserDictWord(surface="ECS", pronunciation="イーシーエス", word_type="PROPER_NOUN", priority=9, accent_type=0),
    UserDictWord(surface="RDS", pronunciation="アールディーエス", word_type="PROPER_NOUN", priority=9, accent_type=0),
    UserDictWord(surface="DynamoDB", pronunciation="ダイナモディービー", word_type="PROPER_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="OpenSearch", pronunciation="オープンサーチ", word_type="PROPER_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="SQS", pronunciation="エスキューエス", word_type="PROPER_NOUN", priority=9, accent_type=0),
    UserDictWord(surface="IaC", pronunciation="アイアック", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="CDK", pronunciation="シーディーケー", word_type="PROPER_NOUN", priority=9, accent_type=0),
    UserDictWord(surface="SAM", pronunciation="サム", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="CloudTrail", pronunciation="クラウドトレイル", word_type="PROPER_NOUN", priority=9, accent_type=4),
    UserDictWord(surface="CloudFront", pronunciation="クラウドフロント", word_type="PROPER_NOUN", priority=9, accent_type=4),
    UserDictWord(surface="CloudWatch", pronunciation="クラウドウォッチ", word_type="PROPER_NOUN", priority=9, accent_type=4),
    UserDictWord(surface="CloudFormation", pronunciation="クラウドフォーメーション", word_type="PROPER_NOUN", priority=9, accent_type=4),
    UserDictWord(surface="ALB", pronunciation="エーエルビー", word_type="PROPER_NOUN", priority=9, accent_type=0),
    UserDictWord(surface="API", pronunciation="エーピーアイ", word_type="PROPER_NOUN", priority=9, accent_type=0),
    UserDictWord(surface="Gateway", pronunciation="ゲートウェイ", word_type="COMMON_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="Glue", pronunciation="グルー", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="Athena", pronunciation="アテナ", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="X-Ray", pronunciation="エックスレイ", word_type="PROPER_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="CodePipeline", pronunciation="コードパイプライン", word_type="PROPER_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="CodeBuild", pronunciation="コードビルド", word_type="PROPER_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="AutoScaling", pronunciation="オートスケーリング", word_type="PROPER_NOUN", priority=9, accent_type=4),
    UserDictWord(surface="Cognito", pronunciation="コグニート", word_type="PROPER_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="VPC", pronunciation="ブイピーシー", word_type="PROPER_NOUN", priority=9, accent_type=0),
    UserDictWord(surface="Lattice", pronunciation="ラティス", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="GitHub", pronunciation="ギットハブ", word_type="PROPER_NOUN", priority=9, accent_type=2),
    UserDictWord(surface="Actions", pronunciation="アクションズ", word_type="COMMON_NOUN", priority=9, accent_type=2),
    UserDictWord(surface="EventBridge", pronunciation="イベントブリッジ", word_type="PROPER_NOUN", priority=9, accent_type=4),
    UserDictWord(surface="StepFunctions", pronunciation="ステップファンクションズ", word_type="PROPER_NOUN", priority=9, accent_type=5),
    UserDictWord(surface="SystemsManager", pronunciation="システムズマネージャー", word_type="PROPER_NOUN", priority=9, accent_type=5),
    UserDictWord(surface="Direct Connect", pronunciation="ダイレクトコネクト", word_type="PROPER_NOUN", priority=9, accent_type=4),
    UserDictWord(surface="Transit Gateway", pronunciation="トランジットゲートウェイ", word_type="PROPER_NOUN", priority=9, accent_type=5),
    UserDictWord(surface="Route53", pronunciation="ルートフィフティースリー", word_type="PROPER_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="NetworkManager", pronunciation="ネットワークマネージャー", word_type="PROPER_NOUN", priority=9, accent_type=5),
    UserDictWord(surface="Budgets", pronunciation="バジェッツ", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="ComputeOptimizer", pronunciation="コンピュートオプティマイザー", word_type="PROPER_NOUN", priority=9, accent_type=5),
    UserDictWord(surface="TrustedAdvisor", pronunciation="トラステッドアドバイザー", word_type="PROPER_NOUN", priority=9, accent_type=5),
    UserDictWord(surface="CostExplorer", pronunciation="コストエクスプローラー", word_type="PROPER_NOUN", priority=9, accent_type=4),
    UserDictWord(surface="GuardDuty", pronunciation="ガードデューティー", word_type="PROPER_NOUN", priority=9, accent_type=4),
    UserDictWord(surface="Config", pronunciation="コンフィグ", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="Control Tower", pronunciation="コントロールタワー", word_type="PROPER_NOUN", priority=9, accent_type=5),
    UserDictWord(surface="Organizations", pronunciation="オーガニゼーションズ", word_type="PROPER_NOUN", priority=9, accent_type=4),
    UserDictWord(surface="SCP", pronunciation="エスシーピー", word_type="PROPER_NOUN", priority=9, accent_type=0),
    UserDictWord(surface="ServiceCatalog", pronunciation="サービスカタログ", word_type="PROPER_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="StackSet", pronunciation="スタックセット", word_type="PROPER_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="Boto3", pronunciation="ボトースリー", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="EC2ImageBuilder", pronunciation="イーシーツーイメージビルダー", word_type="PROPER_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="CI/CD", pronunciation="シーアイシーディー", word_type="PROPER_NOUN", priority=9, accent_type=0),
    UserDictWord(surface="Bedrock", pronunciation="ベッドロック", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="CodeCommit", pronunciation="コードコミット", word_type="PROPER_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="RAM", pronunciation="ラム", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="Health", pronunciation="ヘルス", word_type="COMMON_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="Permissions Boundary", pronunciation="パーミッションズバウンダリー", word_type="PROPER_NOUN", priority=9, accent_type=5),
    UserDictWord(surface="Quota", pronunciation="クォータ", word_type="COMMON_NOUN", priority=9, accent_type=1),
    # 言語・フレームワーク
    UserDictWord(surface="TypeScript", pronunciation="タイプスクリプト", word_type="PROPER_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="JavaScript", pronunciation="ジャバスクリプト", word_type="PROPER_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="Vue.js", pronunciation="ビュージェイエス", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="FastAPI", pronunciation="ファストエーピーアイ", word_type="PROPER_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="bottle", pronunciation="ボトル", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="Gin", pronunciation="ジン", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="Spring Boot", pronunciation="スプリングブート", word_type="PROPER_NOUN", priority=9, accent_type=4),
    UserDictWord(surface="Thymeleaf", pronunciation="タイムリーフ", word_type="PROPER_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="WPF", pronunciation="ダブリューピーエフ", word_type="PROPER_NOUN", priority=9, accent_type=0),
    UserDictWord(surface="HTML5", pronunciation="エイチティーエムエルファイブ", word_type="PROPER_NOUN", priority=9, accent_type=0),
    UserDictWord(surface="jQuery", pronunciation="ジェイクエリー", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="Ajax", pronunciation="エイジャックス", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="CommonJS", pronunciation="コモンジェイエス", word_type="PROPER_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="Fetch", pronunciation="フェッチ", word_type="COMMON_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="JSDoc", pronunciation="ジェイエスドック", word_type="PROPER_NOUN", priority=9, accent_type=0),
    UserDictWord(surface="Python", pronunciation="パイソン", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="Vue", pronunciation="ビュー", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="C#", pronunciation="シーシャープ", word_type="PROPER_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="Go", pronunciation="ゴー", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="Pandas", pronunciation="パンダス", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="PowerShell", pronunciation="パワーシェル", word_type="PROPER_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="ShellScript", pronunciation="シェルスクリプト", word_type="PROPER_NOUN", priority=9, accent_type=4),
    # データベース
    UserDictWord(surface="PostgreSQL", pronunciation="ポストグレスキューエル", word_type="PROPER_NOUN", priority=9, accent_type=4),
    UserDictWord(surface="MySQL", pronunciation="マイエスキューエル", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="Neo4j", pronunciation="ネオフォージェー", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="OSS-DB", pronunciation="オーエスエスディービー", word_type="PROPER_NOUN", priority=9, accent_type=0),
    UserDictWord(surface="SQL", pronunciation="エスキューエル", word_type="PROPER_NOUN", priority=9, accent_type=0),
    UserDictWord(surface="Oracle", pronunciation="オラクル", word_type="PROPER_NOUN", priority=9, accent_type=2),
    UserDictWord(surface="Aurora", pronunciation="オーロラ", word_type="PROPER_NOUN", priority=9, accent_type=0),
    # インフラ・ネットワーク・OS
    UserDictWord(surface="Terraform", pronunciation="テラフォーム", word_type="PROPER_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="Docker", pronunciation="ドッカー", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="Ansible", pronunciation="アンシブル", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="ESXi", pronunciation="イーエスエックスアイ", word_type="PROPER_NOUN", priority=9, accent_type=0),
    UserDictWord(surface="VCSA", pronunciation="ブイシーエスエー", word_type="PROPER_NOUN", priority=9, accent_type=0),
    UserDictWord(surface="Horizon", pronunciation="ホライゾン", word_type="PROPER_NOUN", priority=9, accent_type=2),
    UserDictWord(surface="RHEL", pronunciation="アールヘル", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="CentOS", pronunciation="セントオーエス", word_type="PROPER_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="Ubuntu", pronunciation="ウブントゥ", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="VPN", pronunciation="ブイピーエヌ", word_type="PROPER_NOUN", priority=9, accent_type=0),
    UserDictWord(surface="VLAN", pronunciation="ブイラン", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="GeoLite2", pronunciation="ジオライトツー", word_type="PROPER_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="ArcserveUDP", pronunciation="アークサーブユーディーピー", word_type="PROPER_NOUN", priority=9, accent_type=4),
    UserDictWord(surface="ArcserveBackup", pronunciation="アークサーブバックアップ", word_type="PROPER_NOUN", priority=9, accent_type=4),
    UserDictWord(surface="Systemwalker", pronunciation="システムウォーカー", word_type="PROPER_NOUN", priority=9, accent_type=4),
    UserDictWord(surface="ETERNUS", pronunciation="エターナス", word_type="PROPER_NOUN", priority=9, accent_type=2),
    UserDictWord(surface="BIND", pronunciation="バインド", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="Postfix", pronunciation="ポストフィックス", word_type="PROPER_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="Dovecot", pronunciation="ダブコット", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="FreeRADIUS", pronunciation="フリーレイディウス", word_type="PROPER_NOUN", priority=9, accent_type=4),
    UserDictWord(surface="iSCSI", pronunciation="アイスカジー", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="VDI", pronunciation="ブイディーアイ", word_type="PROPER_NOUN", priority=9, accent_type=0),
    # テスト・ツール
    UserDictWord(surface="Jest", pronunciation="ジェスト", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="pytest", pronunciation="パイテスト", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="testcontainers", pronunciation="テストコンテナーズ", word_type="PROPER_NOUN", priority=9, accent_type=4),
    UserDictWord(surface="Playwright", pronunciation="プレイライト", word_type="PROPER_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="Moto", pronunciation="モト", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="Eclipse", pronunciation="エクリプス", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="Mattermost", pronunciation="マターモスト", word_type="PROPER_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="GitLab", pronunciation="ギットラボ", word_type="PROPER_NOUN", priority=9, accent_type=2),
    UserDictWord(surface="Jira", pronunciation="ジラ", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="draw.io", pronunciation="ドローアイオー", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="Backlog", pronunciation="バックログ", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="PowerAutomate", pronunciation="パワーオートメイト", word_type="PROPER_NOUN", priority=9, accent_type=4),
    UserDictWord(surface="TablePlus", pronunciation="テーブルプラス", word_type="PROPER_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="Herdr", pronunciation="ハーダー", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="devcontainers", pronunciation="デブコンテナーズ", word_type="PROPER_NOUN", priority=9, accent_type=4),
    UserDictWord(surface="Mock", pronunciation="モック", word_type="COMMON_NOUN", priority=9, accent_type=1),
    # その他・略語・一般語
    UserDictWord(surface="CPU", pronunciation="シーピーユー", word_type="PROPER_NOUN", priority=9, accent_type=0),
    UserDictWord(surface="USB", pronunciation="ユーエスビー", word_type="PROPER_NOUN", priority=9, accent_type=0),
    UserDictWord(surface="JWT", pronunciation="ジェイダブリューティー", word_type="PROPER_NOUN", priority=9, accent_type=0),
    UserDictWord(surface="RPA", pronunciation="アールピーエー", word_type="PROPER_NOUN", priority=9, accent_type=0),
    UserDictWord(surface="EIP", pronunciation="イーアイピー", word_type="PROPER_NOUN", priority=9, accent_type=0),
    UserDictWord(surface="Webhook", pronunciation="ウェブフック", word_type="COMMON_NOUN", priority=9, accent_type=2),
    UserDictWord(surface="gzip", pronunciation="ジージップ", word_type="COMMON_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="esbuild", pronunciation="イーエスビルド", word_type="PROPER_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="frontend", pronunciation="フロントエンド", word_type="COMMON_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="backend", pronunciation="バックエンド", word_type="COMMON_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="lint", pronunciation="リント", word_type="COMMON_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="Subagent", pronunciation="サブエージェント", word_type="COMMON_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="Claude Code", pronunciation="クロードコード", word_type="PROPER_NOUN", priority=9, accent_type=2),
    UserDictWord(surface="MiiTel", pronunciation="ミーテル", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="cars MANAGER", pronunciation="カーズマネージャー", word_type="PROPER_NOUN", priority=9, accent_type=4),
    UserDictWord(surface="Intel", pronunciation="インテル", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="Apple Silicon", pronunciation="アップルシリコン", word_type="PROPER_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="Service Worker", pronunciation="サービスワーカー", word_type="PROPER_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="Kubernetes", pronunciation="クバネティス", word_type="PROPER_NOUN", priority=9, accent_type=3),
    UserDictWord(surface="CKA", pronunciation="シーケーエー", word_type="PROPER_NOUN", priority=9, accent_type=0),
    UserDictWord(surface="CCNA", pronunciation="シーシーエヌエー", word_type="PROPER_NOUN", priority=9, accent_type=0),
    UserDictWord(surface="LPIC", pronunciation="エルピック", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="cars", pronunciation="カーズ", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="SaaS", pronunciation="サース", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="FinOps", pronunciation="フィンオプス", word_type="PROPER_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="SRE", pronunciation="エスアールイー", word_type="PROPER_NOUN", priority=9, accent_type=0),
    UserDictWord(surface="nuke", pronunciation="ニューク", word_type="COMMON_NOUN", priority=9, accent_type=1),
    UserDictWord(surface="Dependency Injection", pronunciation="ディペンデンシーインジェクション", word_type="COMMON_NOUN", priority=9, accent_type=5),
    UserDictWord(surface="Graceful Shutdown", pronunciation="グレースフルシャットダウン", word_type="COMMON_NOUN", priority=9, accent_type=5),
]
