import type { Tool } from "./ToolTable";

export const toolData: Tool[] = [
  {
    id: "1",
    name: "Tool A",
    description: "A powerful tool.",
    url: "https://guide-image-tool.metalmental.net",
    status: "Active",
    platform: "Web",
    skills: ["React"],
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "2",
    name: "Tool B",
    description: "A mobile app.",
    url: "https://music.metalmental.net",
    status: "Inactive",
    platform: "Android",
    skills: ["Flutter"],
    createdAt: "2024-02-01T00:00:00Z",
  },
  {
    id: "3",
    name: "Tool C",
    description: "A desktop application.",
    url: "https://code.metalmental.net",
    status: "Active",
    platform: "Windows",
    skills: ["Electron", "TypeScript"],
    createdAt: "2024-03-01T00:00:00Z",
  },
  {
    id: "4",
    name: "Tool D",
    description: "A Chrome extension.",
    url: "https://chrome-extension.metalmental.net",
    status: "Active",
    platform: "Chrome Extension",
    skills: ["Chrome Extension"],
    createdAt: "2024-04-01T00:00:00Z",
  },
  {
    id: "5",
    name: "Tool E",
    description: "A VSCode extension.",
    url: "https://vscode-extension.metalmental.net",
    status: "Inactive",
    platform: "VSCode Extension",
    skills: ["VSCode Extension"],
    createdAt: "2024-05-01T00:00:00Z",
  },
  {
    id: "6",
    name: "Tool F",
    description: "A new tool.",
    url: "https://new-tool.metalmental.net",
    status: "Active",
    platform: "Web",
    skills: ["Vue"],
    createdAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "7",
    name: "Tool G",
    description: "An innovative tool.",
    url: "https://innovative-tool.metalmental.net",
    status: "Inactive",
    platform: "Android",
    skills: ["Flutter", "Python"],
    createdAt: "2024-07-01T00:00:00Z",
  },
  {
    id: "8",
    name: "Tool H",
    description: "A cutting-edge tool.",
    url: "https://cutting-edge-tool.metalmental.net",
    status: "Active",
    platform: "Windows",
    skills: ["C#"],
    createdAt: "2024-08-01T00:00:00Z",
  },
  {
    id: "9",
    name: "Tool I",
    description: "A versatile tool.",
    url: "https://versatile-tool.metalmental.net",
    status: "Inactive",
    platform: "Chrome Extension",
    skills: ["Chrome Extension"],
    createdAt: "2024-09-01T00:00:00Z",
  },
  {
    id: "10",
    name: "Tool J",
    description: "A user-friendly tool.",
    url: "https://user-friendly-tool.metalmental.net",
    status: "Active",
    platform: "VSCode Extension",
    skills: ["VSCode Extension"],
    createdAt: "2024-10-01T00:00:00Z",
  },
];
